#!/usr/bin/env python3
"""Regenerate wiki/index.md + per-type _index.md + wiki/indexes/by-tag/*.md.

Reads wiki/.meta/sources.json and wiki/.meta/backlinks.json (written
by build_meta.py). Shell out to build_meta.py first if they are
missing.

Goals:
    - wiki/index.md stays under ~1K tokens regardless of vault size
      (counts + section links only; never a full list at scale).
    - Per-type _index.md stays under ~10K tokens; auto-shards into
      alphabetical slices when it would exceed that.
    - wiki/indexes/by-tag/{tag}.md emitted for every tag with >=3
      members (smaller clusters live in the type index).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import string
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

TOKEN_CHAR_RATIO = 4  # rough chars-per-token estimate
SHARD_TOKEN_BUDGET = 10_000
SHARD_CHAR_BUDGET = SHARD_TOKEN_BUDGET * TOKEN_CHAR_RATIO
TAG_MIN_MEMBERS = 3

TYPE_DIRS = ["sources", "concepts", "entities", "syntheses", "outputs"]
TYPE_LABELS = {
    "sources": "Sources",
    "concepts": "Concepts",
    "entities": "Entities",
    "syntheses": "Syntheses",
    "outputs": "Outputs",
}


def load_meta(vault: Path) -> tuple[dict, dict]:
    meta = vault / "wiki" / ".meta"
    backlinks = json.loads((meta / "backlinks.json").read_text(encoding="utf-8"))
    sources = json.loads((meta / "sources.json").read_text(encoding="utf-8"))
    return backlinks, sources


def load_page_fm_cache(vault: Path) -> dict[str, dict]:
    """Re-parse frontmatter for every page (needed for titles + tags
    of non-source pages). Kept lightweight: reads first ~60 lines."""
    from build_meta import parse_frontmatter  # local reuse

    out: dict[str, dict] = {}
    for d in TYPE_DIRS:
        root = vault / "wiki" / d
        if not root.exists():
            continue
        for p in sorted(root.rglob("*.md")):
            if p.name.startswith("_index"):
                continue
            head = _read_head(p, 120)
            out[p.stem] = parse_frontmatter(head) | {"_type": d, "_path": p}
    return out


def _read_head(path: Path, lines: int) -> str:
    with path.open("r", encoding="utf-8", errors="replace") as f:
        buf: list[str] = []
        for i, line in enumerate(f):
            buf.append(line)
            if i >= lines:
                break
        return "".join(buf)


# --------------------------------------------------------------------------
# Index rendering
# --------------------------------------------------------------------------

def render_top_index(counts: dict[str, int], tags: list[str], vault: Path) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines: list[str] = []
    lines.append("---")
    lines.append('title: "Index"')
    lines.append("type: output")
    lines.append("status: final")
    lines.append(f"date_modified: {now}")
    lines.append('summary: "Top-level navigation. Generated — do not hand-edit."')
    lines.append("tags:")
    lines.append("  - index")
    lines.append("---")
    lines.append("")
    lines.append("# Wiki index")
    lines.append("")
    lines.append("_Generated by `scripts/shard_index.py`. Do not hand-edit._")
    lines.append("")
    lines.append("## Counts")
    lines.append("")
    lines.append("| Type | Count |")
    lines.append("|---|---|")
    for d in TYPE_DIRS:
        lines.append(f"| {TYPE_LABELS[d]} | {counts.get(d, 0)} |")
    lines.append("")
    lines.append("## Catalogs")
    lines.append("")
    for d in TYPE_DIRS:
        if counts.get(d, 0) == 0:
            continue
        lines.append(f"- [[_index|{TYPE_LABELS[d]}]] — `wiki/{d}/_index.md`")
    lines.append("")
    if tags:
        lines.append("## Tag shards")
        lines.append("")
        for tag in tags:
            lines.append(f"- [[{tag}|#{tag}]] — `wiki/indexes/by-tag/{tag}.md`")
        lines.append("")
    lines.append("## How to find things")
    lines.append("")
    lines.append(
        "- Keyword search: `python3 scripts/wiki_search.py \"<query>\"`"
    )
    lines.append("- Type catalogs (above) are the human-readable listings.")
    lines.append(
        "- `/wiki-query` consults the tag shards first, then the type catalogs, "
        "then the raw files. It does **not** load this index into context on every query."
    )
    lines.append("")
    return "\n".join(lines) + "\n"


def render_type_index(
    type_dir: str, entries: list[dict], vault: Path
) -> list[tuple[Path, str]]:
    """Return list of (path, body) pairs to write. If one page fits in
    the budget, returns a single _index.md. Otherwise returns the
    parent _index.md + alphabetical shards."""
    # Build the lines once; we decide sharding by total size.
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    header = [
        "---",
        f'title: "{TYPE_LABELS[type_dir]} index"',
        "type: output",
        "status: final",
        f"date_modified: {now}",
        f'summary: "Catalog of {TYPE_LABELS[type_dir].lower()}. Generated — do not hand-edit."',
        "tags:",
        "  - index",
        f"  - index-{type_dir}",
        "---",
        "",
        f"# {TYPE_LABELS[type_dir]}",
        "",
        "_Generated by `scripts/shard_index.py`. Do not hand-edit._",
        "",
    ]

    def row(e: dict) -> str:
        title = e.get("title", e["slug"]) or e["slug"]
        summary = (e.get("summary", "") or "").strip().replace("\n", " ")
        return f"- [[{e['slug']}|{title}]] — {summary}"

    entries_sorted = sorted(entries, key=lambda e: (e.get("title") or e["slug"]).lower())
    body_lines = [row(e) for e in entries_sorted]
    full_body = "\n".join(body_lines)

    out_root = vault / "wiki" / type_dir

    # Simple case: fits in one file.
    if len(full_body) <= SHARD_CHAR_BUDGET:
        body = "\n".join(header + body_lines) + "\n"
        return [(out_root / "_index.md", body)]

    # Shard alphabetically. Rough, readable letter buckets.
    buckets: list[tuple[str, str, list[dict]]] = [
        ("a-h", "A–H", []),
        ("i-p", "I–P", []),
        ("q-z", "Q–Z", []),
    ]

    def pick_bucket(title: str) -> int:
        first = (title or "").strip().lower()
        ch = first[0] if first else "z"
        if ch in string.ascii_lowercase:
            if ch <= "h":
                return 0
            if ch <= "p":
                return 1
            return 2
        # digits, symbols, unicode → last bucket
        return 2

    for e in entries_sorted:
        idx = pick_bucket(e.get("title") or e["slug"])
        buckets[idx][2].append(e)

    outputs: list[tuple[Path, str]] = []

    # Parent _index.md points at shards.
    parent_lines = header + [
        f"- [[_index-{slug}|{label}]] — `wiki/{type_dir}/_index-{slug}.md` "
        f"({len(items)} entries)"
        for slug, label, items in buckets
    ]
    outputs.append((out_root / "_index.md", "\n".join(parent_lines) + "\n"))

    # One file per shard.
    for slug, label, items in buckets:
        shard_header = [
            "---",
            f'title: "{TYPE_LABELS[type_dir]} {label}"',
            "type: output",
            "status: final",
            f"date_modified: {now}",
            f'summary: "Catalog shard {label}. Generated — do not hand-edit."',
            "tags:",
            "  - index",
            f"  - index-{type_dir}",
            "---",
            "",
            f"# {TYPE_LABELS[type_dir]} — {label}",
            "",
            f"Parent: [[_index]]",
            "",
        ]
        shard_body = [row(e) for e in items]
        outputs.append(
            (out_root / f"_index-{slug}.md", "\n".join(shard_header + shard_body) + "\n")
        )

    return outputs


def render_tag_shards(
    tags_to_pages: dict[str, list[dict]], vault: Path
) -> list[tuple[Path, str]]:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out: list[tuple[Path, str]] = []
    shard_root = vault / "wiki" / "indexes" / "by-tag"
    shard_root.mkdir(parents=True, exist_ok=True)

    # Clean stale shards first.
    for existing in shard_root.glob("*.md"):
        existing.unlink()

    for tag, pages in sorted(tags_to_pages.items()):
        if len(pages) < TAG_MIN_MEMBERS:
            continue
        header = [
            "---",
            f'title: "#{tag}"',
            "type: output",
            "status: final",
            f"date_modified: {now}",
            f'summary: "Pages tagged #{tag}. Generated — do not hand-edit."',
            "tags:",
            "  - index",
            "  - index-tag",
            f"  - {tag}",
            "---",
            "",
            f"# #{tag}",
            "",
            f"{len(pages)} pages tagged `{tag}`.",
            "",
        ]
        pages_sorted = sorted(pages, key=lambda p: (p.get("title") or p["slug"]).lower())
        rows = [
            f"- [[{p['slug']}|{p.get('title', p['slug'])}]] "
            f"({p.get('_type', '?')}) — "
            f"{(p.get('summary', '') or '').strip().replace(chr(10), ' ')}"
            for p in pages_sorted
        ]
        out.append((shard_root / f"{tag}.md", "\n".join(header + rows) + "\n"))
    return out


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault", default=".", help="repo root containing wiki/")
    args = ap.parse_args()

    vault = Path(args.vault).resolve()
    if not (vault / "wiki").is_dir():
        print(f"error: no wiki/ under {vault}", file=sys.stderr)
        return 2

    # Ensure the meta cache exists.
    meta_dir = vault / "wiki" / ".meta"
    if not (meta_dir / "backlinks.json").exists():
        sys.path.insert(0, str(vault / "scripts"))
        import build_meta  # type: ignore
        built = build_meta.build(vault)
        build_meta.write_meta(vault, built)

    backlinks, sources = load_meta(vault)
    sys.path.insert(0, str(vault / "scripts"))
    page_fm = load_page_fm_cache(vault)

    # Build per-type entry lists.
    by_type: dict[str, list[dict]] = defaultdict(list)
    for slug, node in backlinks["nodes"].items():
        d = node["type"]
        fm = page_fm.get(slug, {})
        entry = {
            "slug": slug,
            "title": fm.get("title", slug),
            "summary": fm.get("summary", ""),
            "tags": fm.get("tags", []) if isinstance(fm.get("tags"), list) else [],
            "_type": d,
        }
        by_type[d].append(entry)

    counts = {d: len(by_type.get(d, [])) for d in TYPE_DIRS}

    # Tag shards.
    tags_to_pages: dict[str, list[dict]] = defaultdict(list)
    for d, entries in by_type.items():
        for e in entries:
            for t in e.get("tags", []) or []:
                if not t:
                    continue
                tags_to_pages[t].append(e)
    tag_shard_writes = render_tag_shards(tags_to_pages, vault)
    emitted_tags = sorted(
        t for t, members in tags_to_pages.items() if len(members) >= TAG_MIN_MEMBERS
    )

    # Write top index.
    top = render_top_index(counts, emitted_tags, vault)
    _atomic_write(vault / "wiki" / "index.md", top)

    # Write per-type indexes (possibly sharded).
    total_shard_files = 0
    for d in TYPE_DIRS:
        # Clear old shards first so renames don't leave strays.
        root = vault / "wiki" / d
        if root.exists():
            for f in root.glob("_index*.md"):
                f.unlink()
        if not by_type.get(d):
            # Still write an empty stub so navigation doesn't 404.
            stub = (
                "---\n"
                f'title: "{TYPE_LABELS[d]} index"\n'
                "type: output\n"
                "status: final\n"
                f'summary: "No {TYPE_LABELS[d].lower()} yet."\n'
                "tags:\n"
                "  - index\n"
                f"  - index-{d}\n"
                "---\n\n"
                f"# {TYPE_LABELS[d]}\n\n"
                "_Empty. Generated by `scripts/shard_index.py`._\n"
            )
            (vault / "wiki" / d).mkdir(parents=True, exist_ok=True)
            _atomic_write(vault / "wiki" / d / "_index.md", stub)
            continue
        writes = render_type_index(d, by_type[d], vault)
        for p, body in writes:
            _atomic_write(p, body)
            total_shard_files += 1

    # Tag shard writes (after clearing happened earlier).
    for p, body in tag_shard_writes:
        _atomic_write(p, body)

    print(
        f"wrote wiki/index.md + {total_shard_files} type-index file(s) "
        f"+ {len(tag_shard_writes)} tag shard(s)"
    )
    return 0


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


if __name__ == "__main__":
    sys.exit(main())
